platform :ios, '9.0'
use_frameworks!

target 'OktaJWT_Tests' do
  pod 'OktaJWT', :path => '../'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = 'YES'
    end
  end
end
